FROM php:8.3-cli-alpine

RUN apk add --no-cache \
        bash \
        curl \
        zip \
        unzip \
        git \
        libzip-dev \
    && docker-php-ext-install \
        pdo_mysql \
        bcmath \
        zip \
        pcntl \
        opcache

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY docker-entrypoint.dev.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["entrypoint.sh"]
